//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyKho.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONVI
    {
        public int ma { get; set; }
        public string tendonvi { get; set; }
        public string chucnang { get; set; }
    }
}
