//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyKho.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HANGHOA()
        {
            this.HANGNHAPs = new HashSet<HANGNHAP>();
            this.HANGXUATs = new HashSet<HANGXUAT>();
        }
    
        public int ma { get; set; }
        public string tenhang { get; set; }
        public string mota { get; set; }
        public string donvitinh { get; set; }
        public Nullable<int> thoigianbaohanh { get; set; }
        public Nullable<int> manhom { get; set; }
    
        public virtual NHOMHANG NHOMHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGNHAP> HANGNHAPs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGXUAT> HANGXUATs { get; set; }
    }
}
