//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyKho.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGNHAP
    {
        public string Spnhap { get; set; }
        public Nullable<int> Slchungtu { get; set; }
        public Nullable<int> Slthucnhap { get; set; }
        public Nullable<int> Sphieubaohang { get; set; }
        public Nullable<int> maHang { get; set; }
    }
}
