//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeThongQuanLyKho.ModelEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public int ma { get; set; }
        public string tenhang { get; set; }
        public string mota { get; set; }
        public string donvitinh { get; set; }
        public Nullable<int> thoigianbaohanh { get; set; }
        public Nullable<int> manhom { get; set; }
        public Nullable<int> soluong { get; set; }
    }
}
