//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONVI
    {
        public DONVI()
        {
            this.NHANVIENs = new HashSet<NHANVIEN>();
        }
    
        public int ma { get; set; }
        public string tendonvi { get; set; }
        public string chucnang { get; set; }
    
        public virtual ICollection<NHANVIEN> NHANVIENs { get; set; }
    }
}
