//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public NHACUNGCAP()
        {
            this.PHIEUNHAPs = new HashSet<PHIEUNHAP>();
        }
    
        public int ma { get; set; }
        public string tenNCC { get; set; }
        public string diachi { get; set; }
        public string sodienthoai { get; set; }
    
        public virtual ICollection<PHIEUNHAP> PHIEUNHAPs { get; set; }
    }
}
