//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHOMHANG
    {
        public NHOMHANG()
        {
            this.HANGHOAs = new HashSet<HANGHOA>();
        }
    
        public int ma { get; set; }
        public string tennhom { get; set; }
        public string tacdung { get; set; }
    
        public virtual ICollection<HANGHOA> HANGHOAs { get; set; }
    }
}
