//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAP
    {
        public string Spnhap { get; set; }
        public Nullable<System.DateTime> ngaynhap { get; set; }
        public string lydonhap { get; set; }
        public Nullable<int> maNCC { get; set; }
        public Nullable<int> maNV { get; set; }
    
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
